### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/research#119]
## Context

A near future vision for the bot: understand all conversations and the state of all projects at any given time by generating embeddings across all of our issues and telegram group chat. 

Some immediate internal use-cases would be: 
- To generate live and accurate q&a for non-operator stakeholders (i.e. investors, partners.) 
- If anybody in the organization has a question about something, instead of asking me or the team, they can ask the bot.
   - This is really useful for when we start hiring our business development team, as I expect them to not be comfortable reading through GitHub pull requests and issues. 
- Onboarding new devs, a q&a bot for the state of any codebase and project status. 

Some external use-cases:
- When a contributor registers their wallet "registers to the DevPool" we can scrape their GitHub and view the specification of every issue that they solved. When a new issue is created, we can recommend the optimal talent to be assigned to that issue. 
- We can view pull request quality (i'm not sure if reviewing code is something that benefits from embeddings though, instead it might make sense to write an internal memo on review quality and "score it") on every registrant and rank talent so we know who to focus our recruiting efforts on more closely. 

This will serve as the kernel of the intelligence of our bot, and I think we should easily be able to build more sophisticated features off of this assuming that the bot "understands" everything. 

If the bot has full context on all I/O of the company, then it has the potential to substitute as a "CEO." Realistically I think it will be a useful assistant for awhile but when more advanced LLMs come around (i.e. gpt5) we should be able to plug it into this infrastructure to allow it to inject all of the necessary context to make informed calculations/projections/decisions. 

## Task

- [ ] 1. generate embeddings for all the repository issues and store on supabase[^1][^2][^3]
   1. supabase has first party support for storing embeddings 
- [ ] 2. generate embeddings for all the codebases the bot is added to and store on supabase. 
   1. i think we can probably take the code from cursor.so, the vscode fork with chatgpt integration 
   2. which you should be using by the way, with gpt4 its incredible; just costly
- [ ] 3. every time there is a pull request opened, the bot should try and automatically link the pull request to the issue that it solves.
   1. this will make working with the bot significantly less rigid, which will allow people to work naturally as they do already. 

[^1]: https://supabase.com/docs/guides/ai/concepts
[^2]: https://github.com/supabase/embeddings-generator
[^3]: https://supabase.com/docs/guides/database/extensions/pgvector

**Comment by 0x4007** [comment]
@gitcoindev I understand that you may have some extra bandwidth and I was wondering if you might be interested to spearhead this project. I plan to break apart the tasks into separate issues with prices after an initial discussion/refinement here.

**Comment by gitcoindev** [comment]
@pavlovcik the concept sounds pretty cool! I will be happy to help on this project once the details are refined and tasks are broken down.

**Comment by 0x4007** [comment]
Regarding recruiting I see two coarse strategies. Push, and pull.

Pull: I envision a future where contributors can log into their own dashboards and see a prioritized list of tasks they are best suited for, based on the similarity to their previously completed work.

Push: we tag them in the GitHub Issue based on their similarly solved issues in the past. This is useful for people who are not registered in our system, as a user acquisition strategy.
